services:
  - type: web
    name: mp4-live-streamer
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: RTMP_URL
        sync: false # Aquí pegarás tu clave de transmisión de YouTube/Twitch
